### ISSUE TITLE
Tabs opening at top and few other options

### ISSUE THREAD

**Issue by greed-d** [scientiac/scifox#1]
Not so adept in firefox CSS but here are some things I wish I had:

- Tabs opening at bottom instead of top
- Back and forward button with the reload button
- A scroll bar cuz I have janky MMB

**Comment by greed-d** [comment]
Ok I got the scroll bar editing the css but can't seem to get the first two

**Comment by scientiac** [comment]
You can comment out 

```
#back-button,
#forward-button,
```

from the 
toolbar section in the userchrome css

and you can get the reload button from customize toolbar option by right clicking the toolbar


i dont understand what you mean by bottom tabs.

**Comment by greed-d** [comment]
https://github.com/user-attachments/assets/9b5e6e9a-1231-4c39-8670-f43cefac0350

This is what I meant by tabs opening at top, I'd like it open tabs to go down not go up

**Comment by greed-d** [comment]
I tried looking in google but no trick worked -_-

**Comment by scientiac** [comment]
https://github.com/mbnuqw/sidebery/issues/662

check this issue... there should be an option in sidebery settings.... for that behavior
