### ISSUE TITLE
About rounded corner fix and other things

### ISSUE THREAD

**Issue by ArtemChandragupta** [scientiac/scifox#2]
Hi, mighty Scientiac! Some time ago we had a conversation on [Reddit](https://www.reddit.com/user/Prize_Sand8284/). I found the code that fixes the white blink on round corners, but I can't get it to work as intended. This is the code ArcWTF copypasted from [edge-frfox](https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/global/browser.css):

```
#appcontent .browserStack {
    margin-inline: var(--uc-tweak-rounded-corners-padding) !important;
    margin-block-end: var(--uc-tweak-rounded-corners-padding) !important;
    border-radius: var(--uc-tweak-rounded-corners-radius) !important;
    box-shadow: var(--uc-tweak-rounded-corners-shadow) !important;
    background-color: var(--tabpanel-background-color) !important;
    position: relative !important;

    /* Use pseudo element overlay to simulate rounded corners, similar to the
     * tab corners, fixes bug with backdrop-filter. */
    &::after {
      content: "";
      position: absolute;
      inset: 0;
      border-radius: inherit;
      /* Draw toolbar background on the negative corner space, then draw the
       * same shadow from the browser window on top. */
      box-shadow:
        var(--uc-tweak-rounded-corners-shadow, 0 0 transparent),
        0 0 0 16px var(--browser-frame-bgcolor) !important;
      clip-path: inset(0);
      pointer-events: none;
    }
  }

```

As you can see, it describes what it does in the comment.

About other things:

```
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] {
  --uc-sidebar-width: 38px !important;
  --uc-sidebar-hover-width: 250px;
  --uc-autohide-sidebar-delay: 600ms; /* Wait 0.3s before hiding sidebar */
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index:1;
}
```
^ there you don't need to set min and max width, as I understand

`[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]` is needed when you have multiple things in your sidebar, not only sidebery. If you use only sidebery, you can remove it.

Also, as I understand, `@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");` is deprecated, so you can remove it.

If you like this comments, I would be happy to make a pr with them.

Also, I have my own nice theme now, which shares quite similar philosophy as your does (but it integrates with a system, not sites, so pages with round corners looks like something in the container and not distract the system stile):

![image](https://github.com/user-attachments/assets/6c6b8e17-91b7-4da3-881b-61d09b84b076)

**Comment by scientiac** [comment]
Hey! This is great, thanks. I'll surely try to fix the issue with this information. BTW your theme looks great, I'd love to steal some of your ideas for the immersive branch, will you be uploading your theme somewhere, like a dotfiles repo?

**Comment by ArtemChandragupta** [comment]
You can see it in my [NixOS config](https://github.com/ArtemChandragupta/NixFlake/tree/main/home-modules/firefox/NixFox)

**Comment by scientiac** [comment]
Thanks, I didn't fix the rounded corners, it didn't fix it but I removed rounded corners altogether in the immersive branch and made some minor improvements on the UX. Set the extensions UI to follow the grid like shyfox. I consider the issue averted than solved. So closing this.
